server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
  #    连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zjl2425228686/springcloud-demo.git #https，不是git
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: spring-cloud-config-dev
---
spring:
  profiles: test
  application:
    name: spring-cloud-config-test